version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    volumes:
      - .:/app
    command: pipenv run python simple.py
