version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    env_file:
      - docker.env
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - PYTORCH_ENABLE_MPS_FALLBACK=1
    volumes:
      - .:/app
      - ./data:/data
    command: pipenv run python simple.py
